# Generated by Django 2.2.3 on 2019-07-31 20:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_pub_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 31, 20, 24, 4, 859362, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
