# Generated by Django 2.2.3 on 2019-08-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190801_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_pub_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
