# Generated by Django 2.2.3 on 2019-07-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_author', models.CharField(max_length=60)),
                ('blog_title', models.CharField(max_length=60)),
                ('blog_description', models.CharField(max_length=250)),
                ('blog_pub_date', models.DateTimeField()),
                ('blog_image', models.ImageField(blank=True, upload_to='images/blog_images/')),
            ],
        ),
    ]
